name: Development

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install

      # Run Lint
      - name: Run Lint
        run: bun run lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: bun run test

      # Upload Coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      # Build Artifact
      - name: Build Artifact
        run: yarn build:dev

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
